### PR TITLE
build new version

### PR DESCRIPTION
**Pull request by egermano**
build new version and change release version

### CODE REVIEW

**Comment by atticoos** [comment]
I haven't gotten a chance to test #6 -- have you integrated that new feature and have experienced it working properly? (I'd assume so)

**Comment by egermano** [comment]
Yes of course. It's just a simple attribute in login function.

**Comment by atticoos** [comment]
Yep, just want to verify all ends before a public release goes out

**Comment by atticoos** [comment]
:+1: thanks!

**Pull request merged**
